# Site settings
title: Title
lang: en
languages: ["fr", "es", "pl", "en"]
email: email@address.com
author: Name
show_downloads: false # "true" or "false" to indicate whether to provide a download URL
show_excerpts: true # set to true to show excerpts on the homepage

# generate social links in footer (only available in some themes, e.g. minima)
twitter_username: a-twitter-username
github_username:  a-github-username

# theme
theme: minima
minima:
  skin: classic

# Permalink structure
permalink: :path

# comments : choose a comments engine, and provide the identifiers
# comments_engine: disqus or talkyard
disqus:
  shortname: a-disqus-shortname
talkyard:
  server_url: https://comments-for-a-website.talkyard.net
  script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js

#plugins
plugins:
  - jemoji

#collections
collections:
  publications:
    output: true
    permalink: :path
  portfolio:
    output: true
    permalink: :path

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      path: "*/index.md"
      type: pages
    values:
      layout: home
  - scope:
      type: portfolio
    values:
      layout: page
  - scope:
      type: publications
    values:
      layout: page
  - scope:
      path: "*/feed.xml"
    values:
      layout: feed
  - scope:
      path: fr
    values:
      lang: fr
  - scope:
      path: en
    values:
      lang: en
  - scope:
      path: es
    values:
      lang: es
  - scope:
      path: pl
    values:
      lang: pl
  - scope:
      path: "_publications/fr"
      type: publications
    values:
      lang: fr
  - scope:
      path: "_publications/en"
      type: publications
    values:
      lang: en
  - scope:
      path: "_publications/es"
      type: publications
    values:
      lang: es
  - scope:
      path: "_publications/pl"
      type: publications
    values:
      lang: pl
  - scope:
      path: "_portfolio/fr"
      type: portfolio
    values:
      lang: fr
  - scope:
      path: "_portfolio/en"
      type: portfolio
    values:
      lang: en
  - scope:
      path: "_portfolio/es"
      type: portfolio
    values:
      lang: es
  - scope:
      path: "_portfolio/pl"
      type: portfolio
    values:
      lang: pl

# Exclude these files from your production_site
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
