title: "alba~math"
email: alba@albamath.com
description: >- # this means to ignore newlines until "baseurl:"
  "Alba Marina MÁLAGA SABOGAL"
show_excerpts: true # set to true to show excerpts on the homepage
  # generate social links in footer
baseurl: "" # the subpath of the site, e.g. /blog
url: "" # the base hostname & protocol for the site, e.g. http://example.com
twitter_username: alba_math
github_username:  albamath

# Build settings
theme: minima

# Exclude these files from your production _site
exclude: README.md
