# Site settings
title: alba~math
lang: fr 
languages: ["fr", "es", "pl", "en"] 
email: alba@albamath.com
logo: /assets/img/cropped-albamath-shaded-logo-small-uncentered-tinified.png
author: Alba MÁLAGA
description: >- # this means to ignore newlines until "show_downloads:"
  Alba Marina MÁLAGA SABOGAL 
  - math research, scientific outreach and general discussion.
show_downloads: false # "true" or "false" to indicate whether to provide a download URL
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of the site, e.g. /blog
url: "http://albamath.com" # the base hostname & protocol for the site, e.g. http://example.com
  # generate social links in footer (only available in some themes, e.g. minima)
twitter_username: alba_math
github_username:  albamath
theme: jekyll-theme-hacker
# Permalink structure (it includes the category in the output, which is useful because we are naming categories after lang)
permalink: none

#collections
collections:
  portfolio:
   output: true
   permalink: /:collection/:name
  cv:
   output: true
   permalink: /:collection/:name
   
# Exclude these files from your production_site
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
